# permissions for end users to edit staticroutes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: router-controller
    app.kubernetes.io/managed-by: kustomize
  name: staticroute-editor-role
rules:
- apiGroups:
  - production-stack.vllm.ai
  resources:
  - staticroutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - production-stack.vllm.ai
  resources:
  - staticroutes/status
  verbs:
  - get
