servingEngineSpec:
  runtimeClassName: ""
  modelSpec:
  - name: "opt125m"
    repository: "eaminchan/opt-125m-cpu"
    tag: "latest"
    modelURL: "facebook/opt-125m"
    replicaCount: 1
    requestCPU: 6
    requestMemory: "16Gi"
    requestGPU: 1
    pvcStorage: "10Gi"
    pvcAccessMode:
      - ReadWriteOnce

  - name: "smol135m"
    repository: "eaminchan/opt-125m-cpu"
    tag: "latest"
    modelURL: "HuggingFaceTB/SmolLM2-135M-Instruct"
    replicaCount: 1
    requestCPU: 6
    requestMemory: "16Gi"
    requestGPU: 1
    pvcStorage: "10Gi"
    pvcAccessMode:
      - ReadWriteOnce

routerSpec:
  repository: "localhost:5000/git-act-router"
  imagePullPolicy: "IfNotPresent"
  enableRouter: true
