servingEngineSpec:
  runtimeClassName: ""
  modelSpec:
  - name: "opt125m"
    repository: "vllm/vllm-openai"
    tag: "latest"
    modelURL: "facebook/opt-125m"

    replicaCount: 1

    requestCPU: 6
    requestMemory: "16Gi"
    requestGPU: 1

    pvcStorage: "10Gi"
    pvcAccessMode:
      - ReadWriteOnce

routerSpec:
  enableRouter: true
  ingress:
    # Builds the ingress resource on the router service
    enabled: true
    className: "nginx"

    # Example annotations
    annotations:
      nginx.ingress.kubernetes.io/enable-access-log: "true"
      nginx.ingress.kubernetes.io/enable-opentelemetry: "true"

    hosts:
      - host: router.example.com
        paths:
          - path: /
            pathType: Prefix
