servingEngineSpec:
  runtimeClassName: ""
  modelSpec:
  - name: "opt125m"
    repository: "vllm/vllm-openai"
    tag: "latest"
    modelURL: "facebook/opt-125m"

    replicaCount: 1

    requestCPU: 2
    requestMemory: "2Gi"
    requestGPU: 1
    limitCPU: "4"
    limitMemory: "4Gi"