servingEngineSpec:
  strategy:
    type: Recreate
  runtimeClassName: ""
  modelSpec:
  - name: "opt125m"
    repository: "vllm/vllm-openai"
    tag: "latest"
    modelURL: "facebook/opt-125m"
    replicaCount: 2
    requestCPU: 6
    requestMemory: "16Gi"
    requestGPU: 0.5

    vllmConfig:
      maxModelLen: 1024
      gpuMemoryUtilization: 0.4
      extraArgs: ["--disable-log-requests"]
