{{- if .Values.routerSpec.enableRouter -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Release.Name }}-router-service-account"
  namespace: {{ .Release.Namespace }}
{{- end }}

{{- if .Values.loraController.enableLoraController }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-lora-controller
  labels:
    app.kubernetes.io/component: lora-controller
    helm-release-name: {{ .Release.Name }}
{{- end }}
