{{- if .Values.routerSpec.enableRouter -}}
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-router-service"
  namespace: {{ .Release.Namespace }}
  {{- if .Values.routerSpec.serviceAnnotations }}
  annotations: {{- toYaml .Values.routerSpec.serviceAnnotations | nindent 4 }}
  {{- end }}
  labels:
  {{- include "chart.routerLabels" . | nindent 4 }}
spec:
  type: {{ .Values.routerSpec.serviceType }}
  ports:
    - name: "router-sport"
      port: {{ .Values.routerSpec.servicePort }}
      targetPort: {{ .Values.routerSpec.containerPort }}
      protocol: TCP
    - name: "lmcache-port"
      port: 9000
      targetPort: lmcache-port
      protocol: TCP
    - name: pd-port-1
      port: 7100
      targetPort: pd-port-1
      protocol: TCP
    - name: pd-port-2
      port: 7200
      targetPort: pd-port-2
      protocol: TCP
    - name: pd-port-3
      port: 7300
      targetPort: pd-port-3
      protocol: TCP
    - name: pd-port-4
      port: 7400
      targetPort: pd-port-4
      protocol: TCP
    - name: pd-port-5
      port: 7500
      targetPort: pd-port-5
      protocol: TCP
  selector:
  {{- include "chart.routerLabels" . | nindent 4 }}
{{- end }}
