{{- if .Values.routerSpec.enableRouter -}}
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-router-service"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}-router-service"
    {{- include "chart.routerLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: {{ .Values.routerSpec.servicePortName }}
      port: {{ .Values.routerSpec.servicePort }}
      targetPort: {{ .Values.routerSpec.containerPort }}
      protocol: TCP
  selector:
  {{- include "chart.routerLabels" . | nindent 4 }}
{{- end }}
