apiVersion: v1
kind: ConfigMap # defines configs through receivers, processors, exporters, and service pipelines
metadata: # define name for use in other files
  name: otel-collector-conf
  namespace: default
data: # how we want to collect tracing data is specified here
  collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024

    exporters:
      logging:
        verbosity: detailed
      otlp:
        endpoint: jaeger-collector.default.svc.cluster.local:4317
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, otlp]
