servingEngineSpec:
  strategy:
    type: Recreate
  runtimeClassName: ""
  modelSpec:
  - name: "opt125m"
    # repository: "eaminchan/opt-125m-cpu"
    repository: "vllm/vllm-openai"
    tag: "latest"
    modelURL: "facebook/opt-125m"
    
    replicaCount: 1

    requestCPU: 1
    requestMemory: "4Gi"
    requestGPU: 1

    pvcStorage: "10Gi"
    pvcAccessMode:
      - ReadWriteOnce

routerSpec:
  resources:
    requests:
      cpu: "1"
      memory: 4G
    limits:
      cpu: "1"
      memory: 4G


# gcloud container clusters get-credentials production-stack --region=us-central1-a
# helm install vllm vllm/vllm-stack -f production_stack_specification.yaml
# helm uninstall vllm
