blank_issues_enabled: true

contact_links:
  - name: Have you read the tutorials?
    url: https://github.com/vllm-project/production-stack/blob/main/tutorials/00-install-kubernetes-env.md
    about: Much help can be found in the docs
  - name: Chat on Slack
    url: https://slack.vllm.ai/
    about: Maybe chatting with the community can help
