apiVersion: production-stack.vllm.ai/v1alpha1
kind: StaticRoute
metadata:
  labels:
    app.kubernetes.io/name: router-controller
    app.kubernetes.io/managed-by: kustomize
  name: staticroute-sample
spec:
  # Service discovery method
  serviceDiscovery: static

  # Routing logic
  routingLogic: roundrobin

  # Comma-separated list of backend URLs
  staticBackends: "http://10.100.245.131:8000,http://10.100.118.139:8000"

  # Comma-separated list of model names
  staticModels: "facebook/opt-6.7b,microsoft/Phi-3-mini-4k-instruct"

  # Reference to the vllm-router service
  routerRef:
    kind: Service
    apiVersion: v1
    name: vllm-router
    namespace: default

  # Health check configuration
  healthCheck:
    # Number of seconds after which the probe times out
    # +optional
    timeoutSeconds: 30

    # Number of seconds between probe attempts
    # +optional
    periodSeconds: 10

    # Minimum consecutive successes for the probe to be considered successful
    # +optional
    successThreshold: 1

    # Minimum consecutive failures for the probe to be considered failed
    # +optional
    failureThreshold: 3

  # Optional: Name of the ConfigMap to create
  configMapName: vllm-router-config
