apiVersion: production-stack.vllm.ai/v1alpha1
kind: LoraAdapter
metadata:
  name: sql-adapter
spec:
  baseModel: "llama2-7b"
  adapterSource:
    type: "huggingface"
    repository: "yard1/llama-2-7b-sql-lora-test"
    adapterName: "sql-adapter"
    credentialsSecretRef:
      name: "huggingface-credentials"
  deploymentConfig:
    algorithm: "default"
