{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vllm-stack-operator.fullname" . }}
  labels:
    {{- include "vllm-stack-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "vllm-stack-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "vllm-stack-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "vllm-stack-operator.fullname" . | trunc 47 | trimSuffix "-" }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vllm-stack-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "vllm-stack-operator.fullname" . | trunc 47 | trimSuffix "-" }}-leader-election
subjects:
  - kind: ServiceAccount
    name: {{ include "vllm-stack-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
