name: CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - '**.py'
      - 'pyproject.toml'
  pull_request:
    paths:
        - '.github/workflows/**'
        - '**.py'
        - 'pyproject.toml'
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python-tests:
    name: Python Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          ignore-nothing-to-cache: true

      - name: Install Dependencies
        run: uv sync --all-extras --all-groups

      - name: Run Tests
        run: uv run pytest
