name: Release vLLM Production Stack Helm Charts

on:
  push:
    branches:
      - main
    paths:
      - "helm/**"

jobs:
  release:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    outputs:
      chart_version: ${{ steps.chart-version.outputs.version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Extract chart version
        id: chart-version
        run: |
          CHART_VERSION=$(grep -oP 'version: \K[0-9]+\.[0-9]+\.[0-9]+' helm/Chart.yaml)
          echo "version=${CHART_VERSION}" >> "$GITHUB_OUTPUT"
          echo "Chart version: ${CHART_VERSION}"

      # Could add Prometheus as a dependent chart here if desired
      # - name: Add Dependency Repos
      #   run: |
      #     helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          skip_existing: false
          packages_with_index: true
          charts_dir: "."
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  release-docker:
    needs: release
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to GitHub Container Registry (GHCR)
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: lmcache
          password: ${{ secrets.LMCACHE_DOCKER_SECRET }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/router:latest
            ghcr.io/${{ github.repository }}/router:v${{ needs.release.outputs.chart_version }}
            ghcr.io/${{ github.repository }}/router:${{ github.sha }}
            lmcache/lmstack-router:latest
            lmcache/lmstack-router:v${{ needs.release.outputs.chart_version }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/router:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/router:buildcache,mode=max
