name: Release vLLM Router Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'src/vllm_router/**'
      - 'docker/**'
      - 'setup.py'

jobs:
  release:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version
        id: version
        run: echo "version=$(python setup.py --version)" >> "$GITHUB_OUTPUT"
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/router:latest
            ghcr.io/${{ github.repository }}/router:${{ steps.version.outputs.version }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/router:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/router:buildcache,mode=max
